OrdererOrgs:
  - Name: OrdererOrg0
    Domain: ordererorg0
    Specs:
      - Hostname: orderer0
PeerOrgs:
  - Name: Org0
    Domain: org0
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org1
    Domain: org1
    Template:
      Count: 2
      Start: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2
    Template:
      Count: 2
      Start: 4
    Users:
      Count: 1
  - Name: Org3
    Domain: org3
    Template:
      Count: 2
      Start: 6
    Users:
      Count: 1
